export const GET_DATA: 'GET_DATA' = 'GET_DATA';
export const GET_DATA_SUCCESS: 'GET_DATA_SUCCESS' = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILED: 'GET_DATA_FAILED' = 'GET_DATA_FAILED';
export const ADD_ITEM: 'ADD_ITEM' = 'ADD_ITEM';
export const UPDATE_PRICE: 'UPDATE_PRICE' = 'UPDATE_PRICE';
export const REMOVE_ITEM: 'REMOVE_ITEM' = 'REMOVE_ITEM';
export const STORE_INGREDIENT: 'STORE_INGREDIENT' = 'STORE_INGREDIENT';
export const POST_ORDER: 'POST_ORDER' = 'POST_ORDER';
export const POST_SUCCESS: 'POST_SUCCESS' = 'POST_SUCCESS';
export const POST_FAILED: 'POST_FAILED' = 'POST_FAILED';
export const MOVE_CONSTRUCTOR_ITEM: 'MOVE_CONSTRUCTOR_ITEM' =
  'MOVE_CONSTRUCTOR_ITEM';
export const GET_TOKEN: 'GET_TOKEN' = 'GET_TOKEN';
export const STORE_TOKEN: 'STORE_TOKEN' = 'STORE_TOKEN';
export const REMOVE_TOKEN: 'REMOVE_TOKEN' = 'REMOVE_TOKEN';
export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' =
  'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' =
  'WS_CONNECTION_CLOSED';

export const baseUrl: string = 'https://norma.nomoreparties.space/api';
export const myToken: string = 'd5b34af3-ad0b-4c78-bdcc-85f9d783b0bc';
